dist: xenial
sudo: required
language: python
cache: pip
python:
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8
- pypy3
install:
  - pip install tox-travis
script:
  - tox
branches:
  only:
    - master
arch:
  - amd64
  - ppc64le
jobs:
  allow_failures:
    - arch: ppc64le
      python: pypy3
